spring.application.name=user-service

server.port=8090

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    health-check-enabled: true
  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info

spring.datasource.url=jdbc:postgresql://localhost:5435/user_db
spring.datasource.username=user_user
spring.datasource.password=user_pass
spring.jpa.hibernate.ddl-auto=update

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
jwt.public-key=classpath:rsa/public_key.pem
