services:
  eureka-server:
    build: ./services/eureka-server
    container_name: eureka-server
    restart: unless-stopped
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker

#  api-gateway:
#    build: ./services/api-gateway
#    container_name: api-gateway
#    restart: unless-stopped
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
#    depends_on:
#      - eureka-server
#      - redis
#    networks:
#      - movie-network

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - movie-network

  movie-db:
    image: postgres:16
    container_name: movie_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: movie_db
      POSTGRES_USER: movie_user
      POSTGRES_PASSWORD: movie_pass
    ports:
      - "5433:5432"
    volumes:
      - movie_db_data:/var/lib/postgresql/data
    networks:
      - movie-network

  auth-db:
    image: postgres:16
    container_name: auth_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
    ports:
      - "5434:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks:
      - movie-network

  user-db:
    image: postgres:16
    container_name: user_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user_user
      POSTGRES_PASSWORD: user_pass
    ports:
      - "5435:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - movie-network

  show-db:
    image: postgres:16
    container_name: show_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: show_db
      POSTGRES_USER: show_user
      POSTGRES_PASSWORD: show_pass
    ports:
      - "5436:5432"
    volumes:
      - show_db_data:/var/lib/postgresql/data
    networks:
      - movie-network

  reservation-db:
    image: postgres:16
    container_name: reservation_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: reservation_db
      POSTGRES_USER: reservation_user
      POSTGRES_PASSWORD: reservation_pass
    ports:
      - "5437:5432"
    volumes:
      - reservation_db_data:/var/lib/postgresql/data
    networks:
      - movie-network
  ai-db:
    image: pgvector/pgvector:pg16
    container_name: ai_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ai_db
      POSTGRES_USER: ai_user
      POSTGRES_PASSWORD: ai_pass
    ports:
      - "5438:5432"
    volumes:
      - ai_db_data:/var/lib/postgresql/data
    networks:
      - movie-network

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - movie-network

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./infrastructure/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./infrastructure/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
      - movie-network

#  user-service:
#    build: ./services/user-service
#    container_name: user-service
#    restart: unless-stopped
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
#      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/user_db
#      SPRING_DATASOURCE_USERNAME: user_user
#      SPRING_DATASOURCE_PASSWORD: user_pass
#    depends_on:
#      - eureka-server
#      - user-db
#      - rabbitmq
#    networks:
#      - movie-network
#
#  movie-service:
#    build: ./services/movie-service
#    container_name: movie-service
#    restart: unless-stopped
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
#      SPRING_DATASOURCE_URL: jdbc:postgresql://movie-db:5432/movie_db
#      SPRING_DATASOURCE_USERNAME: movie_user
#      SPRING_DATASOURCE_PASSWORD: movie_pass
#    depends_on:
#      - eureka-server
#      - movie-db
#    networks:
#      - movie-network
#
#  reservation-service:
#    build: ./services/reservation-service
#    container_name: reservation-service
#    restart: unless-stopped
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
#      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/user_db
#      SPRING_DATASOURCE_USERNAME: user_user
#      SPRING_DATASOURCE_PASSWORD: user_pass
#    depends_on:
#      - eureka-server
#      - user-db
#      - rabbitmq
#    networks:
#      - movie-network
#
#  payment-service:
#    build: ./services/payment-service
#    container_name: payment-service
#    restart: unless-stopped
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
#      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/user_db
#      SPRING_DATASOURCE_USERNAME: user_user
#      SPRING_DATASOURCE_PASSWORD: user_pass
#    depends_on:
#      - eureka-server
#      - user-db
#      - rabbitmq
#    networks:
#      - movie-network
#
#  auth-service:
#    build: ./services/auth-service
#    container_name: auth-service
#    restart: unless-stopped
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
#      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/auth_db
#      SPRING_DATASOURCE_USERNAME: auth_user
#      SPRING_DATASOURCE_PASSWORD: auth_pass
#    depends_on:
#      - eureka-server
#      - auth-db
#      - rabbitmq
#    networks:
#      - movie-network
#
#  show-service:
#    build: ./services/show-service
#    container_name: show-service
#    restart: unless-stopped
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
#      SPRING_DATASOURCE_URL: jdbc:postgresql://show-db:5432/show_db
#      SPRING_DATASOURCE_USERNAME: show_user
#      SPRING_DATASOURCE_PASSWORD: show_pass
#    depends_on:
#      - eureka-server
#      - show-db
#    networks:
#      - movie-network
#
volumes:
  movie_db_data:
  auth_db_data:
  user_db_data:
  show_db_data:
  rabbitmq_data:
  reservation_db_data:
  redis_data:
  ai_db_data:
  ollama_data:
#
networks:
  movie-network:
    driver: bridge