services:
  movie-db:
    image: postgres:16
    container_name: movie_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: movie_db
      POSTGRES_USER: movie_user
      POSTGRES_PASSWORD: movie_pass
    ports:
      - "5433:5432"
    volumes:
      - movie_db_data:/var/lib/postgresql/data

  auth-db:
    image: postgres:16
    container_name: auth_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
    ports:
      - "5434:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  user-db:
    image: postgres:16
    container_name: user_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user_user
      POSTGRES_PASSWORD: user_pass
    ports:
      - "5435:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data

  show-db:
    image: postgres:16
    container_name: show_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: show_db
      POSTGRES_USER: show_user
      POSTGRES_PASSWORD: show_pass
    ports:
      - "5436:5432"
    volumes:
      - show_db_data:/var/lib/postgresql/data

  reservation-db:
    image: postgres:16
    container_name: reservation_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: reservation_db
      POSTGRES_USER: reservation_user
      POSTGRES_PASSWORD: reservation_pass
    ports:
      - "5437:5432"
    volumes:
      - reservation_db_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./infrastructure/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./infrastructure/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro

volumes:
  movie_db_data:
  auth_db_data:
  user_db_data:
  show_db_data:
  rabbitmq_data:
  reservation_db_data: