spring.application.name=auth-service

spring.datasource.url=jdbc:postgresql://localhost:5432/movie-booking
spring.datasource.username=postgres
spring.datasource.password=pass123

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=t


jwt.private-key=classpath:rsa/private_key.pem
jwt.public-key=classpath:rsa/public_key.pem

jwt.access-token.expiration=86400000
jwt.refresh-token.expiration=604800000