spring.application.name=auth-service

spring.datasource.url=jdbc:postgresql://localhost:5434/auth_db
spring.datasource.username=auth_user
spring.datasource.password=auth_pass
spring.jpa.hibernate.ddl-auto=update

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
