spring.application.name=auth-service
server.port=8081
# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    health-check-enabled: true
  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=t


jwt.private-key=classpath:rsa/private_key.pem
jwt.public-key=classpath:rsa/public_key.pem

jwt.access-token.expiration=86400000
jwt.refresh-token.expiration=604800000


spring.datasource.url=jdbc:postgresql://localhost:5434/auth_db
spring.datasource.username=auth_user
spring.datasource.password=auth_pass

spring.jpa.hibernate.ddl-auto=update

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

google.client-id=322111702009-bkc62icl9bob1fr42ef9imk1362cbve4.apps.googleusercontent.com
