spring.application.name=reservation-service

server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5437/reservation_db
spring.datasource.username=reservation_user
spring.datasource.password=reservation_pass


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.public-key=classpath:rsa/public_key.pem