spring.application.name=payment-service

server.port=8088

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.healthcheck.enabled=true
eureka.instance.prefer-ip-address=true
eureka.instance.health-check-url-path=/actuator/health
eureka.instance.status-page-url-path=/actuator/info

spring.datasource.url=jdbc:postgresql://localhost:5435/user_db
spring.datasource.username=user_user
spring.datasource.password=user_pass
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

stripe.api-key=${STRIPE_SECRET_KEY:sk_test_51Tomsa62JToXF5px2Va2Y1Mk0VHAPTWOr91GhVdrQuqxNpslX6IRnNH6AEBbozxwUxrBtZGqY8B66eIDteG7WSK600xfk9DB9R}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET:whsec_9768b864d89e7d129fc30e1eb4fa51a0413bcf61ed2a8c67085819a59a07de5f}
stripe.success-url=${STRIPE_SUCCESS_URL:http://localhost:4200/reservations}
stripe.cancel-url=${STRIPE_CANCEL_URL:http://localhost:4200/reservations}
stripe.currency=${STRIPE_CURRENCY:usd}

jwt.public-key=classpath:rsa/public_key.pem

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
