spring.application.name=movie-service

server.port=8084

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    health-check-enabled: true
  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info

spring.datasource.url=jdbc:postgresql://localhost:5433/movie_db
spring.datasource.username=movie_user
spring.datasource.password=movie_pass

#spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.public-key=classpath:rsa/public_key.pem
